### ISSUE TITLE
Dead links to this project

### ISSUE THREAD

**Issue by jzaefferer** [reststate/reststate-mobx#60]
https://mobx.reststate.org is gone, but there's important links to this domain, like here https://howtojsonapi.com/react.html or here https://jsonapi.org/implementations/

https://mobx.reststate.codingitwrong.com works, so maybe that dead domain can be revived as a redirect?

**Comment by CodingItWrong** [comment]
Thanks for the heads up. I run howtojsonapi so I’ve updated the links there. And I’ve submitted a PR to jsonapi.org, they usually merge them petty quickly.

**Comment by CodingItWrong** [comment]
Alright, jsonapi.org is fixed now, so all these links should now be working
